# mongo+mongo-express
version: "3.8"
name: mongodbnew

networks:
  mongodb_network:
    driver: bridge

volumes:
  mdb:
    name: mdb
  mdbcfg:
    name: mdbcfg

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mdb:/data/db
      - mdbcfg:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: admin
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: rootuser
      ME_CONFIG_BASICAUTH_PASSWORD: rootpass
      ME_CONFIG_MONGODB_URL: "mongodb://rootuser:rootpass@host.docker.internal:27017/admin?ssl=false"	
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - mongodb_network
